# Site settings
title: Meng Fanze
description: "求知，思考，高效生活"
url: 'http://iFanze.cn'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: '孟凡泽'
  email: iFanze@outlook.com
  qq: '919446762'
  weibo_username: 'ichen0201'
  github_username:  iFanze
  zhihu_username:  iFanze

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:month/:title/
markdown: kramdown
highlighter: rouge
#highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
